FROM oven/bun:1-debian AS build
WORKDIR /app
COPY bun.lock package.json ./
RUN bun install --production --frozen-lockfile
COPY . .
RUN bunx prisma generate
RUN NODE_ENV=production bun run build

FROM oven/bun:1-debian AS runner
WORKDIR /app
COPY --from=build /app/dist/app.js .
EXPOSE 3000
CMD ["bun", "app.js"]