---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCZCCmG+QKdxbDZauUuF0ESbqyWoJ0ZaOM/GdLPtqURYR23hzNpb6metdxLfg4gXcTg6FoQ1lowQeSlVsMddLFFEXMigLAmH+8rltNSK/fObJvn3lSA9CVIpwaNN8VFCJyQRjnsqdiN98GMP5y9cI+VWamkqHqiAb4upPveccJd5BpK+YSZAx69V3RD8fp5bBl8w94npBkN1F4JDLgW11N4+IKhnQNPbSVyDBI6l9Agbg/R1ABDdcgK3UJJ5qmT2mHouEuMJoBjKA7vaPO85//ERJ/7MUje6A59titsdNx/V06dMATLpmWjbiR/E2+zNCeJFUKIJQ9H4PNBnD6GM6pOU6jDHcFEhX3LPAFIw0/KNtCm49uwySR+zcv4Oa1U73D4Ya2QBX1p22u8jD4lQ9yrQUfy8aTWvZHVkSNwFHokYUcSKRO+OKLPQVjoH5Om8iJa1oyB0qDdStw9bPHLN0RyCo7+uzuO+UjMjE7zy+LQME0Vl65y2i8u8o0KdrsZSyHTJY6xuNLsezB71JIw89g5iF7XnWwFFCboae+xXAApxtLJF2r9ZzpRbT8+9TlIKuodJIi+Vvc162Gvi58rrMNqKloV0TsJUNP8BG6T5jaOhIKXiVVRsAMLgS64j17l8uDe6hSSP4EyCctRk1BVJc567/jj8dOVgHpKF7VTvgmWbp8fZLhk8mEf1T9SD+r2LyprOnitLMmOhShwr2/psr/eRQa20YoJ27J4FEZjctRx8nVmKaRMP0FK7CbP6vD2EqPSCLhpVQRoy50LGVN4DUVHMHErQxAJfZml9UA3GeOYGiNT2CAcvAhDboHWIuMIHRqHuEzU7kXeW/orEnbBM78yhLESL6Q8tx1LzzBzkmKPM0y815yjYCPQEUuBHqXRL0eKnfhZZBxJSv0LQ9pK3ps/73uR0gvmlG+2BP0z8YrubVvoY3xlcWSTZt8IIUZdoaS5F/5jBYjBZw6ROIUsUqozJWRg
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
